# Generated by Django 4.1.3 on 2022-12-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0005_alter_dish_dish_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ["id"]},
        ),
    ]
